(TeX-add-style-hook "d_period"
 (function
  (lambda ()
    (LaTeX-add-labels
     "period.detailed"
     "period.folder"
     "period.folder.dialog"
     "period.aliasgap"
     "period.aliasgap.dialog"
     "period.special"
     "period.special.dialog"
     "period.ampvar"
     "period.ampvar.dialog"
     "period.calculate"
     "period.calculate.message"
     "period.predict"
     "period.predict.dialog"
     "period.artificial"
     "period.artificial.dialog"
     "period.recalculate"
     "period.residuals.dialog"
     "period.epochs"
     "period.epochs.dialog"
     "period.import"
     "period.export"
     "period.cleanfrequencies"
     "period.phase"
     "period.phase.window"
     "period.phase.binning"
     "period.phase.binning.dialog"
     "period.phase.frequency"
     "period.phase.frequency.dialog"
     "period.phase.frequency.other.dialog"))))

