SOURCES= \
  fourier.cpp \
  dfourier.cpp \
  dfcalc.cpp \
  dtimepnt.cpp \
  dtimestr.cpp \
  dperipnt.cpp \
  dtnames.cpp \
  str.cpp \
  dcolors.cpp \
  dfroutin.cpp

fourier: $(SOURCES)
	c++ -O3 -I. -o fourier $(SOURCES)
